"""
Enhanced Alberta Energy AI Visualization Agent - agent.py
Clean Multi-Agent Architecture with Artifact-Based Data Flow
"""

from typing import Dict, Any
from google.adk.agents import LlmAgent, SequentialAgent
from google.adk.tools import FunctionTool
import asyncio

# Import centralized tools
from .tools import (
    get_sql_query,
    create_viz_code_from_query,
    execute_code_and_save_plots
)
from .config import vizConfig
config = vizConfig()

# =============================================================================
# AGENT 1: SQL DATA RETRIEVAL AGENT
# =============================================================================

sql_data_agent = LlmAgent(
    name="sql_data_retrieval_agent",
    model=config.default_model,
    description="Retrieves SQL data and saves as artifacts for visualization pipeline",
    instruction="""You are a SQL Data Retrieval Specialist.

Your job is to:
1. Take the user's natural language request for data
2. Use the get_sql_data_and_save_artifact tool to:
   - Generate appropriate SQL query
   - Execute the query against the database
   - Save the retrieved data as an artifact
   - Store metadata in session state for the next agent

The tool will automatically:
- Generate SQL from natural language
- Execute the query safely
- Save data as a JSON artifact with timestamp
- Store minimal metadata (filename, SQL query, row count) in state

Always use the tool with the user's original data request.
Provide clear feedback about data retrieval and artifact creation.

Example responses:
- "Retrieved 150 rows of energy production data and saved as artifact sql_data_20250806_143022.json"
- "Found 85 renewable energy facilities matching your criteria, data ready for visualization"
""",
    
    tools=[FunctionTool(get_sql_query)],
    output_key="sql_retrieval_result"
)

# =============================================================================
# AGENT 2: VISUALIZATION CODE GENERATOR AGENT
# =============================================================================

visualization_generator = LlmAgent(
    name="intelligent_visualization_generator",
    model=config.default_model,
    description="Loads data artifacts and generates optimal Python visualization code using LLM",
    instruction="""You are an expert Data Visualization Code Generator.

Your job is to:
1. Understand the user's visualization requirements
2. Use the create_viz_code_from_query tool which will:
    - Load the data from sql query saved in session state
    - Analyze the data structure (columns, types, sample rows)
    - Make an intelligent LLM call to generate appropriate visualization code
    - Consider the user's specific visualization request
    - Store the generated code in session state abd return a message of success or failure


Always use the tool with the user's visualization requirements.
The tool uses advanced prompt engineering to ensure the LLM generates high-quality, executable code.

""",
    
    tools=[FunctionTool(create_viz_code_from_query)]
)

# =============================================================================
# AGENT 3: CODE EXECUTION AGENT
# =============================================================================

code_executor_agent = LlmAgent(
    name="code_execution_agent",
    model=config.default_model,
    description="Executes Python visualization code and saves plots as artifacts",
    instruction="""You are a Python Code Execution Specialist.

Your job is to:
1. Take the generated Python code from session state
2. Use the execute_code_and_save_plots tool to:
   - Execute the visualization code safely
   - Capture any generated matplotlib/seaborn plots
   - Save plots as PNG artifacts with high quality
   - Provide execution feedback and artifact information

The tool will automatically:
- Execute code in a controlled environment
- Configure matplotlib for headless operation
- Detect and save all generated figures
- Create timestamped PNG artifacts
- Store artifact metadata in session state
- Handle any execution errors gracefully

Always use the tool to execute the code generated by the previous agent.
Provide clear feedback about execution status and saved artifacts.

Example responses:
- "Successfully executed code and saved 2 visualization artifacts: bar_chart_20250806_143045.png and trend_analysis_20250806_143045.png"
- "Code executed successfully - created interactive energy dashboard saved as visualization_20250806_143045.png"
- "Execution completed with 1 high-resolution plot artifact ready for download"
""",
    
    tools=[FunctionTool(execute_code_and_save_plots)],
    output_key="execution_result"
)

# =============================================================================
# ROOT COORDINATOR AGENT
# =============================================================================

root_agent = SequentialAgent(
    name="alberta_energy_viz_coordinator",
    description="Enhanced SQL → Artifact → Code Generation → Execution Pipeline",
    sub_agents=[
        sql_data_agent,
        visualization_generator, 
        code_executor_agent
    ]
)

# =============================================================================
# VERSION INFO
# =============================================================================

__version__ = "6.0.0"
__description__ = "Enhanced multi-agent system with artifact-based data flow and LLM-powered code generation"

__all__ = [
    "root_agent",
    "sql_data_agent", 
    "visualization_generator",
    "code_executor_agent"
]